version: '3.8'

services:

  flask_app:
    container_name: dcat_flask_app
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 7000:7000
    depends_on:
      - postgresql
    networks:
      - default

  postgresql:
    container_name: dcat_postgresql
    build: ./postgres
    volumes:
      - /data/storage/data-catalog:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    networks:
      - default
