name: docker 
on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:

env:
  REPOSITORY_MAIN_BRANCH: "master"
  DOCKER_IMAGE_REPOSITORY: mintproject
  DOCKER_IMAGE_NAME: data_catalog 
  DOCKER_DATABASE_IMAGE_NAME: data_catalog_db 

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v2

      - name: Create environment variable with the commit id
        run: |
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Expose the commit id
        id: exposeValue
        run: |
          echo "::set-output name=docker_tag::${{ env.DOCKER_TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: API Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: api
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.branch-name.outputs.current_branch }}, ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          build_args: |
            MAPGL_ACCESS_TOKEN: ${{ secrets.MAPGL_ACCESS_TOKEN }}

      - name: API Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: api 
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          build-args: |
            MAPGL_ACCESS_TOKEN: ${{ secrets.MAPGL_ACCESS_TOKEN }}



      - name: Database Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: postgres
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:${{ steps.branch-name.outputs.current_branch }}, ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Database Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: postgres
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:latest